routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\PanelController;
use App\Http\Controllers\UserController;
use App\Models\Param;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::middleware(['auth'])->get('welcome', function () {
    $start = Param::where('code', 'rat_start')->first()->value;
    $end = Param::where('code', 'rat_end')->first()->value;

    $startDate = \Carbon\Carbon::createFromFormat('d-m-Y H:i', $start);
    $endDate = \Carbon\Carbon::createFromFormat('d-m-Y H:i', $end);

    $today = \Carbon\Carbon::today();
    $before = $today->lessThan($startDate);
    $after = $today->greaterThan($endDate);

    return view('welcome', [
        'startDate' => $startDate,
        'before' => $before,
        'after' => $after
    ]);
})->name('welcome');

Route::middleware(['auth'])->group(function () {
    Route::get('change-password', [ChangePasswordController::class, 'index'])->name('password.index');
    Route::put('change-password', [ChangePasswordController::class, 'store'])->name('password.store');

    Route::middleware(['period'])->group(function () {
        Route::get('/', [HomeController::class, 'index'])->name('home');
        Route::get('/profile-koperasi', [HomeController::class, 'profile'])->name('profile');
        Route::get('/pengurus-koperasi', [HomeController::class, 'committee'])->name('committee');
        Route::get('/tanggapan-rapat', [HomeController::class, 'feedback'])->name('feedback');
        Route::post('/tanggapan-rapat', [HomeController::class, 'submit_feedback'])->name('feedback.submit');
        Route::get('/materi-rapat', [HomeController::class, 'material'])->name('material');
    });
});


Route::prefix('panel')->middleware(['auth', 'admin'])->group(function () {
    Route::get('/', [PanelController::class, 'index'])->name('panel');

    Route::prefix('users')->group(function () {
        Route::get('/', [UserController::class, 'index'])->name('users');
        Route::get('/{id}/edit', [UserController::class, 'edit'])->name('users.edit');
        Route::put('/{id}', [UserController::class, 'update'])->name('users.update');
        Route::delete('/{id}', [UserController::class, 'destroy'])->name('users.delete');
        Route::post('/all', [UserController::class, 'allUsers']);
        Route::post('/upload-users-file', [UserController::class, 'uploadUsersFile']);
        Route::post('/{user}/reset-password', [UserController::class, 'resetPassword'])->name('users.reset');
    });

    Route::resource('materials', MaterialController::class)->names('materials');

    Route::get('feedback', [FeedbackController::class, 'index'])->name('panel.feedback');
    Route::post('feedback', [FeedbackController::class, 'export'])->name('feedback.export');
});

Route::get('/send-invitation', [UserController::class, 'sendInvitation']);

Route::get('/cek-nomor-anggota', [AccountController::class, 'index'])->name('check-account.index');
Route::post('/cek-nomor-anggota', [AccountController::class, 'check'])->name('check-account.check');

app/Http/Controllers/PanelController.php
<?php

namespace App\Http\Controllers;

use App\Models\Feedback;
use App\Models\LoginLog;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;

class PanelController extends Controller
{
    public function index()
    {
        $admin = User::where('username', '00000000')->first();

        $users_all = User::where('id', '!=', $admin->id)->count();
        $users_present = count(LoginLog::select('user_id')
            ->where('user_id', '!=', $admin->id)
            ->groupBy('user_id')
            ->get());
        $users_absence = $users_all - $users_present;

        $feedback_all = Feedback::where('user_id', '!=', $admin->id)->count();
        $feedback_agree = Feedback::where('agreement', 'y')->where('user_id', '!=', $admin->id)->count();
        $feedback_disagree = $feedback_all - $feedback_agree;
        $have_not_decided = $users_present - $feedback_agree - $feedback_disagree;

        $users_present_percentage =
            $users_all == 0 ? 0 : 100 * $users_present / $users_all;
        $feedback_agree_percentage =
            $feedback_all == 0 ? 0 :  100 * $feedback_agree / $users_present;
        $feedback_disagree_percentage =
            $feedback_all == 0 ? 0 : 100 * $feedback_disagree / $users_present;

        return view(
            'pages.panel.index',
            [
                'users_all' => $users_all,
                'users_present' => $users_present,
                'users_absence' => $users_absence,
                'feedback_all' => $feedback_all,
                'feedback_agree' => $feedback_agree,
                'feedback_disagree' => $feedback_disagree,
                'have_not_decided' => $have_not_decided,
                'users_present_percentage' => number_format($users_present_percentage, 2),
                'feedback_agree_percentage' => number_format($feedback_agree_percentage, 2),
                'feedback_disagree_percentage' => number_format($feedback_disagree_percentage, 2),
            ]
        );
    }
}

resources/views/pages/panel/materi/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 d-none d-md-block">
      <div class="card" data-aos="fade-up" data-aos-delay="300">
        <div class="card-body">
          <x-sidebar-menu type="panel" activeMenu="materials" />
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <div class="card full-height" data-aos="zoom-in">
        <div class="my-3 m-md-4">
          <div class="container">
            <h3>Create Materi</h3>
            <hr>

            @if ($errors->any())
            <div class="alert alert-danger">
              <ul class="m-0">
                @foreach ($errors->all() as $error)
                <li> {{ $error }} </li>
                @endforeach
              </ul>
            </div>
            @endif

            <form action="{{ route('materials.store') }}" method="POST" enctype="multipart/form-data">

              @csrf

              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ old('title') }}" autofocus
                      required>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="document">Document</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" name="document" class="custom-file-input" id="document" accept=".pdf"
                          required>
                        <label class="custom-file-label" for="document">Choose file</label>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="col-md-12">
                  <div class="form-group">
                    <label for="body">Body</label>
                    <textarea name="body" id="editor" class="form-control">{{ old('body') }}</textarea>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="sequence">Sequence</label>
                    <input type="number" class="form-control" id="sequence" name="sequence"
                      value="{{ old('body') ?? "99" }}" required>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="is_active">Active</label>
                    <select name="is_active" id="is_active" class="form-control">
                      <option value="n">Inactive</option>
                      <option value="y">Active</option>
                    </select>
                  </div>
                </div>
              </div>

              <div class="row my-3">
                <div class="col text-right">
                  <button type="submit" class="btn btn-success px-5">Save</button>
                </div>
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
@endsection

@push('addon-scripts')
<script src="https://cdn.ckeditor.com/4.15.0/standard/ckeditor.js"></script>
<script>
  CKEDITOR.replace('editor');
</script>
@endpush

resources/views/pages/panel/materi/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 d-none d-md-block">
      <div class="card" data-aos="fade-up" data-aos-delay="300">
        <div class="card-body">
          <x-sidebar-menu type="panel" activeMenu="materials" />
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <div class="card full-height" data-aos="zoom-in">
        <div class="my-3 m-md-4">
          <div class="container">
            <h3>Update Materi</h3>
            <hr>

            @if ($errors->any())
            <div class="alert alert-danger">
              <ul class="m-0">
                @foreach ($errors->all() as $error)
                <li> {{ $error }} </li>
                @endforeach
              </ul>
            </div>
            @endif

            <form action="{{ route('materials.update', $data->id) }}" method="POST" enctype="multipart/form-data">
              @method('PUT')
              @csrf

              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ $data->title }}" autofocus
                      required>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="document">Document</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" name="document" class="custom-file-input" id="document" accept=".pdf">
                        <label class="custom-file-label" for="document">Choose file</label>
                      </div>
                    </div>
                    <small class="form-text text-muted">Kosongkan jika tidak ingin mengganti.
                      @if ($data->document_path)
                      <a href="{{ Storage::url($data->document_path) }}" target="_blank">preview file saat ini.</a>
                      @endif
                    </small>
                  </div>
                </div>

                <div class="col-md-12">
                  <div class="form-group">
                    <label for="body">Body</label>
                    <textarea name="body" id="editor" class="form-control">
                      {!! $data->body !!}
                    </textarea>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="sequence">Sequence</label>
                    <input type="number" class="form-control" id="sequence" name="sequence"
                      value="{{ $data->sequence ?? 99 }}" required>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form-group">
                    <label for="is_active">Active</label>
                    <select name="is_active" id="is_active" class="form-control">
                      <option value="n" @if ($data->is_active == 'n') selected @endif>Inactive</option>
                      <option value="y" @if ($data->is_active == 'y') selected @endif>Active</option>
                    </select>
                  </div>
                </div>
              </div>

              <div class="d-flex justify-content-end my-3">
                <button type="submit" class="btn btn-success px-4 mr-1">Save</button>
                <a href="{{ route('materials.index') }}" class="btn btn-light px-4">Cancel</a>
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
@endsection

@push('addon-scripts')
<script src="https://cdn.ckeditor.com/4.15.0/standard/ckeditor.js"></script>
<script>
  CKEDITOR.replace('editor');
</script>
@endpush

resources/views/pages/panel/materi/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 d-none d-md-block">
      <div class="card" data-aos="fade-up" data-aos-delay="300">
        <div class="card-body">
          <x-sidebar-menu type="panel" activeMenu="materials" />
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <div class="card full-height" data-aos="zoom-in">
        <div class="my-3 m-md-4">
          <div class="container">
            <h3>Materi</h3>
            <hr>
            <x-alert />

            <a href="{{ route('materials.create') }}" class="btn btn-primary mb-3">Tambah Baru</a>

            <div class="table-responsive">
              <table class="table table-hover scroll-horizontal-vertical w-100" id="resultTable">
                <thead>
                  <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Sequence</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody></tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
@endsection

@push('addon-scripts')
<script>
  const  dataTable = $('#resultTable').DataTable({
			processing: true,
			serverSide: true,
			ordering: true,
			ajax: {
				url: '{!! url()->current() !!}'
			},
			columns: [
				{	data: 'title', name: 'title' },
				{	data: 'sequence', name: 'sequence' },
				{	data: 'is_active', name: 'is_active' },
				{	
					data: 'action', 
					name: 'action',
					orderable: false,
					searchable: false,
					width: '15%',
          className: 'text-center'
				},
			],
      order: [
        [1, 'asc'],
        [0, 'asc'],
      ]
	})
</script>
@endpush

resources/views/pages/panel/materi/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 d-none d-md-block">
      <div class="card" data-aos="fade-up" data-aos-delay="300">
        <div class="card-body">
          <x-sidebar-menu type="panel" activeMenu="materials" />
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <div class="card full-height" data-aos="zoom-in">
        <div class="my-3 m-md-4">
          <div class="container">
            <h3>Preview Materi</h3>
            <hr>

            <div class="mb-4">
              <h4>{{ $data->title }}</h4>

              <div class="my-4">
                {!! $data->body !!}
              </div>

              @if ($data->document_path)
              <div id="adobe-dc-view" style="height: 90vh"></div>
              <script src="https://documentservices.adobe.com/view-sdk/viewer.js"></script>
              <script type="text/javascript">
                document.addEventListener("adobe_dc_view_sdk.ready", function()
                  {
                    var adobeDCView = new AdobeDC.View({clientId: "{{ config('services.adobe.key') }}", divId: "adobe-dc-view"});
                      adobeDCView.previewFile(
                      {
                        content: {location: {url: "{{ Storage::url($data->document_path) }}"}},
                        metaData: {fileName: "{{ $data->document_origin_name }}"}
                      },{
                        defaultViewMode: "FIT_WIDTH", 
                        showAnnotationTools: false, 
                        showLeftHandPanel: false,
                        dockPageControls: false, 
                        showDownloadPDF: false, 
                        showPrintPDF: false
                      });
                  });
              </script>
              @endif
            </div>


            <div class="d-flex justify-content-between">
              <div>
                <form action="{{ route('materials.destroy', $data->id) }}" method="POST">
                  @csrf @method('DELETE')
                  <button type="submit" class="btn btn-danger px-3">Delete</button>
                </form>
              </div>

              <div>
                <a href="{{ route('materials.edit', $data->id) }}" class="btn btn-primary px-4 mr-1">Edit</a>
                <a href="{{ route('materials.index') }}" class="btn btn-light px-4">Back</a>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

  </div>
</div>
@endsection